name: Build OpenWrt Docker x86-64 image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"

env:
  FIRMWARE_URL: "https://github.com/Bchuanggit/sshaction/suites/1217497183/artifacts/18191641"
  REPOSITORY: Bchuanggit/sshaction
  TAG: 19.07.2

jobs:
  build:
    name: "Build OpenWrt docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Firmware
        run: |
          wget $FIRMWARE_URL -O openwrt.tar.gz

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          FIRMWARE: openwrt.tar.gz
        with:
          name: ${{ env.REPOSITORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          buildargs: FIRMWARE
          tags: "latest,${{ env.TAG }}"
